repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    exclude: ^\.github/workflows/

-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
        language_version: python3
        files: ^(ai|gui)/.*\.py$
    exclude: ^\.github/workflows/

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        files: ^(ai|gui)/.*\.py$
    exclude: ^\.github/workflows/

-   repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
    -   id: clang-format
        files: ^server/.*\.(c|h)$
    exclude: ^\.github/workflows/
