name: GUI Client Build and Test

on:
  push:
    branches: [ dev, main ]
    paths:
      - 'gui/**'
      - '.github/workflows/gui-build.yml'
  pull_request:
    branches: [ dev, main ]
    paths:
      - 'gui/**'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        cd gui
        pip install -r requirements.txt
        pip install pytest pytest-cov flake8
        
    - name: Install GUI dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pygame
    
    - name: Lint with flake8
      run: |
        cd gui
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test with pytest
      run: |
        cd gui
        pytest --cov=./ --cov-report=xml
    
    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        directory: ./gui/
        flags: gui