name: Issue Management

on:
  issues:
    types: [opened, labeled, unlabeled, assigned, unassigned]
  pull_request:
    types: [opened, closed, reopened]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC

jobs:
  issue-management:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Authenticate with GitHub CLI
        run: echo "${{ secrets.PROJECT_MANAGEMENT_TOKEN }}" | gh auth login --with-token

      - name: Move new issues to Backlog
        if: github.event_name == 'issues' && github.event.action == 'opened'
        run: gh issue edit ${{ github.event.issue.number }} --add-project 'Zappy Development' --column Backlog

      - name: Move assigned issues to To Do
        if: github.event_name == 'issues' && github.event.action == 'assigned'
        run: gh issue edit ${{ github.event.issue.number }} --add-project 'Zappy Development' --column 'To Do'

      - name: Move PRs to Review
        if: github.event_name == 'pull_request' && github.event.action == 'opened'
        run: gh pr edit ${{ github.event.pull_request.number }} --add-project 'Zappy Development' --column Review

      - name: Move PRs to Done when closed
        if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true
        run: gh pr edit ${{ github.event.pull_request.number }} --add-project 'Zappy Development' --column Done